image: Visual Studio 2017
build_script:
- cmd: dotnet build src --configuration Release
test_script:
- ps: >-
    dotnet test "src\Tests\Tests.csproj" --configuration Release --no-build

    dotnet test "src\NServiceBusTests\NServiceBusTests.csproj" --configuration Release --no-build

    dotnet test "src\RebusTests\RebusTests.csproj" --configuration Release --no-build
artifacts:
- path: nugets\**\*.nupkg